version: '3.5'

services:
    nginx:
        image: nginx:latest
        ports:
            - "8303:80"
            - "4403:443"
        volumes:
            - ./docker/nginx/hosts:/etc/nginx/conf.d
            - ./:/var/www
            - ./logs/nginx/:/var/log/nginx:cached
        depends_on:
            - php
    php:
        build:
            context: ./
            dockerfile: ./docker/php/Dockerfile
        container_name: payment_api_app
        user: "${UID}"
        volumes:
          - ./:/var/www
          - ./data/composer:/.composer
          - ./logs/lumen:/var/www/var/logs:cached
        depends_on:
            - mysql
    mysql:
        image: mysql:5.7.21
        environment:
            MYSQL_ROOT_PASSWORD: discover9100Ylumenapi
            MYSQL_DATABASE: discover_paymentapi
        ports:
            - "8903:3306"
        volumes:
            - ./data/mysql:/var/lib/mysql